### ISSUE TITLE
v1.4.7-v1.7.4 can not parse a apk that can be installed normally on devices 

### ISSUE THREAD

**Issue by SuoNayi-GitHub** [xiaxiaocao/apk-parser#21]
it fails to parse a apk that can be installed normally on phones and can be parsed by AAPT.
the following is the stack trace when parse fails:

Exception in thread "main" java.lang.NullPointerException
	at net.dongliu.apk.parser.struct.xml.Attribute.toStringValue(Attribute.java:27)
	at net.dongliu.apk.parser.parser.XmlTranslator.onAttribute(XmlTranslator.java:83)
	at net.dongliu.apk.parser.parser.CompositeXmlStreamer.onAttribute(CompositeXmlStreamer.java:33)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.readXmlNodeStartTag(BinaryXmlParser.java:165)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.parse(BinaryXmlParser.java:88)
	at net.dongliu.apk.parser.ApkParser.parseManifestXml(ApkParser.java:155)
	at net.dongliu.apk.parser.ApkParser.getApkMeta(ApkParser.java:70)
please contact me if more detail is required.

**Comment by xiaxiaocao** [comment]
fixed in 1.7.5 & 2.0.5.  see https://github.com/xiaxiaocao/apk-parser/commit/3eb6fa2bf51baa7b972470ceed0ea5a7aceef403

**Comment by SuoNayi-GitHub** [comment]
thx
