### ISSUE TITLE
apkFile.getAllIcons() throws exception.

### ISSUE THREAD

**Issue by SamHoque** [xiaxiaocao/apk-parser#82]
Here is the stacktrace 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:55)
	at net.dongliu.apk.parser.AbstractApkFile.parseResourceTable(AbstractApkFile.java:391)
	at net.dongliu.apk.parser.AbstractApkFile.parseManifest(AbstractApkFile.java:188)
	at net.dongliu.apk.parser.AbstractApkFile.getIconPaths(AbstractApkFile.java:312)
	at net.dongliu.apk.parser.AbstractApkFile.getAllIcons(AbstractApkFile.java:251)
	at Main.downloadApks(Main.java:32)
	at Main.main(Main.java:16)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at net.dongliu.apk.parser.utils.ResourceLoader.toReader(ResourceLoader.java:62)
	at net.dongliu.apk.parser.utils.ResourceLoader.loadSystemStyles(ResourceLoader.java:41)
	at net.dongliu.apk.parser.struct.resource.ResourceTable.<clinit>(ResourceTable.java:18)
	... 7 more
```

Link to apk file: https://lynxkik.org/kik/remix/LynxRemixV1.5.6.1.apk

Edit: Looks like every resource related feature throws the same exception

**Comment by hsiafan** [comment]
I try to parse the apk file, with the latest version 2.6.6, seems work well. 
Please try the version 2.6.6 to see if errors are gone.
